- assert:
    that: 
      - '_version != ""'

- include: docker.yml

- name: install apt packages
  apt: "name='{{ item }}' state=present"
  with_items:
    - git
    - python-pip

- name: install docker-py
  pip: name=docker-py version=0.3.1

- name: create build directory
  file: >
    dest="{{ _build_dir }}"
    state=directory

- name: generate templates
  template: >
    src="{{ item.src }}"
    dest="{{ _build_dir }}/{{ item.dest }}"
  with_items:
    - { src: "Dockerfile", dest: "Dockerfile" }
    - { src: "eibd.sh", dest: "eibd.sh" }

- name: build image
  sudo: yes
  docker_image: >
    name="{{ _image_name }}"
    tag="{{ _image_tag }}"
    path="{{ _build_dir }}"
    state=build

#- name: tag
#  command: >
#    docker tag -f
#    {{ _image_name }}:{{ _image_tag }}
#    {{ _image_name }}:{{ _extra_tag }}
#  when: _extra_tag != ''
